@startuml

title __EXCEPTION's Class Diagram__\n

  namespace br.com.apibancaria {
    namespace exception {
      class br.com.apibancaria.exception.ChavePixJaCadastradaException {
          + ChavePixJaCadastradaException()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace exception {
      class br.com.apibancaria.exception.ChavePixNaoEncontradaException {
          + ChavePixNaoEncontradaException()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace exception {
      class br.com.apibancaria.exception.ClienteNaoEncontradoException {
          + ClienteNaoEncontradoException()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace exception {
      class br.com.apibancaria.exception.ContaInativaException {
          + ContaInativaException()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace exception {
      class br.com.apibancaria.exception.ContaNaoEncontradaException {
          + ContaNaoEncontradaException()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace exception {
      class br.com.apibancaria.exception.CpfJaCadastradoException {
          + CpfJaCadastradoException()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace exception {
      class br.com.apibancaria.exception.CredenciaisInvalidasException {
          + CredenciaisInvalidasException()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace exception {
      class br.com.apibancaria.exception.EmailJaCadastradoException {
          + EmailJaCadastradoException()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace exception {
      class br.com.apibancaria.exception.SaldoInsuficienteException {
          + SaldoInsuficienteException()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace exception {
      class br.com.apibancaria.exception.TransferenciaParaSiMesmoException {
          + TransferenciaParaSiMesmoException()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
