@startuml

title __REQUEST's Class Diagram__\n

  namespace br.com.apibancaria {
    namespace dto.request {
      class br.com.apibancaria.dto.request.ChavePixRequest {
          - chave : String
          - idConta : Long
          + ChavePixRequest()
          + chave()
          + idConta()
          + tipo()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace dto.request {
      class br.com.apibancaria.dto.request.ClienteRequest {
          - cpf : String
          - email : String
          - nome : String
          - senha : String
          - telefone : String
          + ClienteRequest()
          + cpf()
          + email()
          + nome()
          + senha()
          + telefone()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace dto.request {
      class br.com.apibancaria.dto.request.DepositoRequest {
          - valor : BigDecimal
          + DepositoRequest()
          + valor()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace dto.request {
      class br.com.apibancaria.dto.request.LoginRequest {
          - email : String
          - senha : String
          + LoginRequest()
          + email()
          + senha()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace dto.request {
      class br.com.apibancaria.dto.request.PixRequest {
          - chavePixDestino : String
          - contaOrigemId : Long
          - valor : BigDecimal
          + PixRequest()
          + chavePixDestino()
          + contaOrigemId()
          + valor()
      }
    }
  }
  

  namespace br.com.apibancaria {
    namespace dto.request {
      class br.com.apibancaria.dto.request.SaqueRequest {
          - valor : BigDecimal
          + SaqueRequest()
          + valor()
      }
    }
  }
  

  br.com.apibancaria.dto.request.ChavePixRequest o-- br.com.apibancaria.enums.TipoChavePix : tipo


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
